config/routes.rb
Organizer::Application.routes.draw do

  resources :suit_status_changes

  resources :protocols

  resources :suits

  resources :events

  resources :categories
  
  resources :comments, :only => [:destroy]

  resources :users do
    collection do
      put :update_profile
    end
  end

  resources :contacts do
    resources :notes do
      member do
        post :comment
      end
    end
    member do
      get :confirm_destroy
      get :avatar
      put :favorite
    end
    collection do
      post :print
    end
  end

  resources :preferences do
    collection do
      get :profile
      get :dashboard
      put :update_dashboard
    end
  end

  resources :tasks do
    member do
      put :complete
      post :comment
      post :postpone
    end
    collection do
      get :get_tasks
      get :week
      get :next_week
      get :completed
    end
  end
  
  
  match '/calendar' => 'calendar#index', :as => :calendar
  match '/summary' => 'home#summary', :as => :summary
  match '/profile' => 'users#profile', :as => :profile
  
  match '/search' => 'home#search', :as => :search
  match '/search/city' => 'home#search_city', :as => :search_city
  match '/search/occupation' => 'home#search_occupation', :as => :search_occupation
  match '/search/weather' => 'home#search_weather', :as => :search_weather

  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :home, :only => [:index]

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "home#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
  acts_as_commentable
  belongs_to :user
  belongs_to :contact
  
  scope :last_notes, order("date DESC").limit(10)
  scope :by_date, order("date DESC")
  
  def self.search_everything(query)
    if query.present?
      q = "%#{query.downcase}%"
      where(['lower(name) LIKE ?', q]).order("date DESC")
    else
      order("date DESC").limit(5)
    end
  end
  
  validates_presence_of :date, :name
  
  def date_string
    date.to_s
  end
  
  def date_string=(date)
    self.date = Time.zone.parse(date)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :require_user
  respond_to :html, :js

  # GET /notes
  # GET /notes.xml
  def index
    @contact = current_user.contacts.find(params[:contact_id])
    @notes = @contact.notes.by_date

    respond_with @notes
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @contact = current_user.contacts.find(params[:contact_id])
    @note = current_user.notes.find(params[:id])
    @comment = @note.comments.new

    respond_with @note
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @contact = current_user.contacts.find(params[:contact_id])
    @note = @contact.notes.build
    @note.date = Time.now

    respond_with @note
  end

  # GET /notes/1/edit
  def edit
    @contact = current_user.contacts.find(params[:contact_id])
    @note = @contact.notes.find(params[:id])

    respond_with @note
  end

  # POST /notes
  # POST /notes.xml
  def create
    @contact = current_user.contacts.find(params[:contact_id])
    @note = Note.new(params[:note])
    @note.contact = @contact
    @note.user = current_user

    respond_with @note do |format|
      if @note.save
        @notes = @contact.notes.last_notes
        format.html { redirect_to(@contact, :notice => t('messages.created')) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @contact = current_user.contacts.find(params[:contact_id])
    @note = @contact.notes.find(params[:id])

    respond_with @note do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to([@contact,@note], :notice => t('messages.updated')) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @contact = current_user.contacts.find(params[:contact_id])
    @note = @contact.notes.find(params[:id])
    @note.destroy

    respond_with @note do |format|
      format.html { redirect_to(@contact, :notice => t('messages.note.removed')) }
    end
  end
  
  def comment
    @contact = current_user.contacts.find(params[:contact_id])
    @note = @contact.notes.find(params[:id])
    @comment = @note.comments.new(params[:comment])
    @comment.update_attribute(:user_id, current_user)
    
    respond_with @comment do |format|
      format.html { redirect_to([@contact,@note], :notice => t('messages.comment.created')) }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_comments.html.erb
<%= content_for :javascript do %>
	$(function() {
		$(".comments .comment").live("mouseover mouseout", function(event){
			if (event.type == 'mouseover') {
				$(this).find(".list_options").show();
			} else {
				$(this).find(".list_options").hide();
			}
		});
	});
<% end %>

<% unless @note.comments.empty? %>
<h3 class="nice_blue"><%=t "application.note.comments" %></h3>
<% end %>
<% @note.comments.each do |c| %>
<div id="<%= dom_id(c) %>" class="comment">
	<h3>
		<span class="gray_medium"><%=l c.created_at %></span>

		<%= link_to inline_ui_icon("remove", :title => t("application.comment.remove")), comment_path(c), :class => "list_options inline", :method => :delete, :remote => true, :confirm => "#{t("application.confirm", :default => "Are you sure?")}" %>

	</h3>
	<%= simple_format(c.comment) %>
</div>
<% end %>

app/views/notes/_form.html.erb
<%= content_for :javascript do %>
	$(function() {
		$("textarea").elastic();
		
		$.datepicker.setDefaults( $.datepicker.regional[ "<%= I18n.locale %>" ] );
		$( "#datepicker" ).datepicker({
			altField: "#alternate",
			altFormat: "yy-mm-dd",
			showOtherMonths: true,
			selectOtherMonths: false,
			changeMonth: true,
			changeYear: true,
			dateFormat: "yy-mm-dd",
			defaultDate: "<%=l @note.date, :format => :datepicker %>"
		});
	});
<% end %>

<% semantic_form_for [@contact, @note] do |form| %>

	<%= form.inputs :class => "column_left right_border", :style => "width: 270px; margin-right: 20px;" do %>
		<%= form.input :date_string, :as => :hidden, :input_html => { :id => "alternate" } %>
		<li>
			<%= form.label :date_string %>
			<div id="datepicker" style="width: 250px"></div>
		</li>
	<% end %>
	<%= form.inputs :class => "column_left" do %>
		<%= form.input :name, :input_html => { :rows => 4 } %>
	<% end %>
	
	<fieldset></fieldset>
	<hr />
	<div class="group navform wat-cf">
	  <%= submit_button %>
	</div>
<% end %>

app/views/notes/_inline_form.html.erb
<%= content_for :javascript do %>
	$(function() {
		$("#note_options a").live("click", function(e){
			e.preventDefault();
			$(this).parent().addClass("hidden");
			$("#note_date_select").removeClass("hidden");
		});
	});
<% end %>

<h3><%= t "texts.contact.new_note", :name => @contact.first_name %></h3>
<p id="note_intro"><%= t "texts.contact.new_note_desc" if @contact.notes.size == 0 %></p>

<% semantic_form_for [@contact, @note], :html => {:id => "add_new_note", :class => "inline"}, :remote => true do |form| %>
	<%= form.inputs do %>
	<%= form.input :name, :label => false, :input_html => { :rows => 2 } %>
	<span id="note_options" class="inline-options underline float_left"><a href="#"><%= t"application.set_date" %></a> (<%= t"application.if_note_not_for_today" %>)</span>
	<span id="note_date_select" class="hidden float_left"><%= form.date_select :date %></span>
	<div class="right"><%= submit_button :back => :none, :icon => "add", :label => "Adicionar" %></div>
	<% end %>
<% end %>

app/views/notes/_list.html.erb
<%= content_for :javascript do %>
	$(function() {
	});
<% end %>

<% if @notes.size > 0 %>
<h3><%= inline_ui_icon("color user") %> <%= t "application.notes" %></h3>
<% end %>

<ul class="contact_show_list notes">
	<% @notes.each do |note| %>
		<li id="<%= dom_id note %>">
			<div class="list_options">
				<a href="<%= contact_note_path(@contact, note) %>" class="list_option show"><%=t "application.details" %></a>
			</div>
			<h4>
				<% if note.date.year == Date.today.year %>
					<%=l note.date, :format => :simple_no_year %>
				<% else %>
					<%=l note.date, :format => :simple %>
				<% end %>
				<% unless note.comments.empty? %>
					<%= inline_ui_icon("comment", :title => t("texts.note.has_comments")) %>
				<% end %>
			</h4>
			<p><%= note.name %></p>
		</li>
	<% end %>
</ul>

app/views/notes/_table.html.erb
<table class = "table">
	<% @notes.each do |note| %>
	<tr class   = "<%= cycle("odd", "even") %>">
		<td>
			<h4><%= I18n.l note.date, :format => :simple %></h4>
			<%= note.name %>
		</td>
		<td class="last">
			<%= link_to "#{t("application.edit", :default => "Edit")}", edit_contact_note_path(note.contact, note) %> |
			<%= link_to "#{t("application.delete", :default => "Delete")}", contact_note_path(note.contact, note), :method => :delete, :confirm => "#{t("application.confirm", :default => "Are you sure?")}" %>
		</td>
	</tr>          
	<% end -%>
</table>

app/views/notes/comment.js.erb
<% @object_dom = dom_id(@comment) %>

$(".comment_form form")[0].reset();
$('.formtastic').valtastic();

$(".comments").html("<%= escape_javascript(render(:partial => "notes/comments"))%>")
$("#<%= @object_dom %>").effect("highlight", {}, 1500);

app/views/notes/create.js.erb
<% @object_dom = dom_id(@note) %>
<% @note = Note.new(:date => Time.now) %>

$("#note_inline_form").replaceWith("<%= escape_javascript(render(:partial => "notes/inline_form"))%>");
$('.formtastic').valtastic();

$("#note_list").html("<%= escape_javascript(render(:partial => "notes/list"))%>");
$("#<%= @object_dom %>").effect("highlight", {}, 1500);

app/views/notes/destroy.js.erb
<% @object_dom = dom_id(@note) %>
$("#<%= @object_dom %>").fadeThenSlideUp(2000);

app/views/notes/edit.html.erb
<div class="block">       
  <div class="content">
	<div class="content-header">
		<h2><%= t("application.edit", :default => "Edit") %> <%= t("activerecord.models.note", :default => "Note").downcase %> <%= t "application.about" %> <%= link_to @note.contact.name, @note.contact %></h2>
	</div>
    <div class="inner">
        <%= render :partial => "form" %>
    </div>
  </div>
</div>

<% content_for :sidebar do %>
	<div class="block notice">
		<ul class="navigation">
			<li class="last"><%= link_to t("application.note.back_to_contact"), @note.contact %></li>
		</ul>
	</div>
<% end %>

app/views/notes/index.html.erb
<div class="block">   
	<div class="content">
		<div class="content-header">
			<div class="control">
				<%= link_to_new(Note) %>
			</div>
			<h2 class="title">
				<%= link_to @contact.name, contact_path(@contact) %> &raquo;
				<%= t("application.notes", :default => "Note")  %>
			</h2>
		</div>
		<div class="inner">
			<div id="data_view">
				<%= render :partial => "table" %>
			</div>
			<div id="data_pagination">
				
			</div>              
			<br />
			<div class='wat-cf'></div>
		</div>
	</div>
</div>

<%= content_for :sidebar, render(:partial => "contacts/sidebar") %>

app/views/notes/new.html.erb
<div class="block">         
  <div class="content">
	<div class="content-header">
    	<h2><%= t("application.new", :default => "New")%>  <%= t("activerecord.models.note", :default => "Note") %></h2>
	</div>
    <div class="inner">
        <%= render :partial => "form" %>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/notes/show.html.erb
<div class="block">       
	<div class="content">
		<div class="content-header">
			<h2><%= t("activerecord.models.note", :default => "Note") %> <%= t "application.about" %> <%= link_to @note.contact.name, @note.contact %></h2>
		</div>
		<div class="inner">
			<h4 class="nice_blue">
				<% if @note.date.year == Date.today.year %>
					<%=l @note.date, :format => :simple_no_year %>
				<% else %>
					<%=l @note.date, :format => :simple %>
				<% end %>
			</h4>
			
			<%= simple_format @note.name %>
			
			<hr />
			<div class="data_details gray_small">
				<p><strong><%=t "activerecord.attributes.note.created_at" %>:</strong> <%=l @note.created_at %></p>
				<% if @note.created_at != @note.updated_at %>
				<p><strong><%=t "activerecord.attributes.note.updated_at" %>:</strong> <%=l @note.updated_at %></p>
				<% end %>
			</div>
			<hr />
			
			<div class="comment_form">
				<h3><%= t "texts.comment.new" %> <%= t "texts.note.about_this" %></h3>

				<% semantic_form_for [@comment], :html => {:id => "add_new_comment", :class => "inline"}, :url => comment_contact_note_path(@contact, @note), :remote => true do |form| %>
					<%= form.inputs do %>
					<%= form.input :comment, :label => false, :input_html => { :rows => 2 } %>
					<div class="right"><%= submit_button :back => :none, :icon => "add", :label => "Adicionar" %></div>
					<% end %>
				<% end %>
			</div>
			<div class="clear"></div>
			<hr />
			<div class="comments">
				<%= render :partial => "comments" %>
			</div>
		</div>
	</div>
</div>

<% content_for :sidebar do %>
	<div class="block notice">
		<ul class="navigation">
			<li><%= link_to t("application.note.back_to_contact"), @note.contact %></li>
			<li><%= link_to "Alterar nota", edit_contact_note_path(@note.contact, @note) %></li>
			<li class="last"><%= link_to "Remover nota", contact_note_path(@note.contact, @note), :method => :delete, :confirm => "#{t("application.confirm", :default => "Are you sure?")}" %></li>
		</ul>
	</div>
<% end %>