config/routes.rb
Organizer::Application.routes.draw do

  resources :suit_status_changes

  resources :protocols

  resources :suits

  resources :events

  resources :categories
  
  resources :comments, :only => [:destroy]

  resources :users do
    collection do
      put :update_profile
    end
  end

  resources :contacts do
    resources :notes do
      member do
        post :comment
      end
    end
    member do
      get :confirm_destroy
      get :avatar
      put :favorite
    end
    collection do
      post :print
    end
  end

  resources :preferences do
    collection do
      get :profile
      get :dashboard
      put :update_dashboard
    end
  end

  resources :tasks do
    member do
      put :complete
      post :comment
      post :postpone
    end
    collection do
      get :get_tasks
      get :week
      get :next_week
      get :completed
    end
  end
  
  
  match '/calendar' => 'calendar#index', :as => :calendar
  match '/summary' => 'home#summary', :as => :summary
  match '/profile' => 'users#profile', :as => :profile
  
  match '/search' => 'home#search', :as => :search
  match '/search/city' => 'home#search_city', :as => :search_city
  match '/search/occupation' => 'home#search_occupation', :as => :search_occupation
  match '/search/weather' => 'home#search_weather', :as => :search_weather

  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :home, :only => [:index]

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  acts_as_commentable
  
  scope :overdue, where("due_at < ? AND completed = ?", Date.today, false).order("due_at ASC")
  scope :not_overdue, where("due_at >= ? AND completed = ?", Date.today, false).order("due_at ASC")
  scope :incomplete, where(:completed => false)
  scope :complete, where(:completed => true)
  scope :last_tasks, where("completed = ?", false).order("due_at ASC")
  
  scope :due_to_today, where( :due_at => (Time.zone.now.at_midnight)..(Time.zone.now.end_of_day) ).order("created_at DESC")
  
  scope :due_to_tomorrow, where( :due_at => (Time.zone.now.at_midnight+1.day)..(Time.zone.now.end_of_day+1.day) ).order("created_at DESC")
  
  scope :due_to_this_week, where( :due_at => (Time.zone.now.at_midnight+1.day)..(Time.zone.now.at_midnight.end_of_week) ).order("due_at ASC")
  
  scope :due_to_next_week, where( :due_at => (Time.zone.now.end_of_week.at_midnight+1.day)..(Time.zone.now.end_of_week.end_of_day+1.week) ).order("due_at ASC")
  
  scope :due_to_later, where("date(due_at) > ?", Date.today.end_of_week+1.week).order("due_at ASC")
  
  def self.search_everything(query)
    if query.present?
      q = "%#{query.downcase}%"
      where({:completed => false}).where(['lower(name) LIKE ?', q]).order("created_at DESC")
    else
      where({:completed => false}).order("created_at DESC").limit(5)
    end
  end
  
  belongs_to :user
  belongs_to :contact
  
  has_many :categorization
  has_many :categories, :through => :categorization
  
  validates_presence_of :name
  # validates_presence_of :start_at_time, :due_at_date, :due_at_time, :if => Proc.new{|s| !s.all_day and s.start_at_date.present? }
  
  def overdue?
    due_at < Date.today and completed == false
  end
  
  def due_to_today?
    due_at == Date.today
  end
  
  def due_to_until_today?
    due_at <= Date.today
  end
  
  # date virtual attribute to start_at as a string
  
  def start_at_date
    I18n.l self.start_at, :format => :default if self.start_at.present?
  end
  
  def start_at_date=(date)
    #self.update_attribute(:start_at, DateTime.strptime("#{date} #{self.start_at_time_utc}", "#{I18n.t("datetime.formats.default")}"))
    if date.present?
      @date = DateTime.strptime("#{date}", "#{I18n.t("datetime.formats.date")}")
    else
      @date = Time.zone.now
    end
    if self.start_at.present?
      @time = self.start_at
    else
      @time = Time.zone.now.midnight
    end
    self.start_at = Time.zone.parse("#{@date.year}-#{@date.month}-#{@date.day} #{@time.hour}:#{@time.min}") if date.present?
  end
  
  # time virtual attribute to due_at as a string
  
  def due_at_date
    I18n.l self.due_at, :format => :datepicker if self.due_at.present?
  end
  
  def due_at_date=(date)
    if date.present?
      @date = DateTime.strptime("#{date}", "%Y-%m-%d")
    else
      @date = Time.zone.now
    end
    if self.due_at.present?
      @time = self.due_at
    else
      @time = Time.zone.now.midnight
    end
    self.due_at = Time.zone.parse("#{@date.year}-#{@date.month}-#{@date.day} #{@time.hour}:#{@time.min}") if date.present?
  end
  
  def due_at_time
    if self.due_at.present?
      I18n.l self.due_at, :format => :time
    else
      "00:00"
    end
  end
  
  def due_at_time_utc
    I18n.l self.due_at.utc, :format => :time
  end
  
  def due_at_time=(time)
    if time.present?
      @time = Time.zone.parse(time)
    else
      @time = Time.zone.now
    end
    if self.due_at.present?
      @date = self.due_at
    else
      @date = Time.zone.now
    end
    self.due_at = Time.zone.parse("#{@date.year}-#{@date.month}-#{@date.day} #{@time.hour}:#{@time.min}") if time.present?
    rescue ArgumentError
      @due_at_time_invalid = true
  end
  
  def validate
    errors.add(:due_at_time, I18n.t("activerecord.errors.messages.invalid")) if @due_at_time_invalid
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :require_user
  respond_to :html, :js

  # GET /tasks
  # GET /tasks.xml
  def index
    @overdue = current_user.tasks.overdue
    @today = current_user.tasks.incomplete.due_to_today
    @week = week
    @next_week = next_week
    @later = current_user.tasks.incomplete.due_to_later
    
    @empty = (@overdue + @today + @week + @next_week + @later).size == 0
    
    @incomplete = current_user.tasks.incomplete
    
    respond_with @tasks
  end
  
  def week
    @week = current_user.tasks.incomplete.due_to_this_week
  end

  def next_week
    @next_week = current_user.tasks.incomplete.due_to_next_week
  end
  
  def completed
    @completed = current_user.tasks.complete.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = current_user.tasks.find(params[:id])
    @contact = @task.contact
    @comment = @task.comments.new

    respond_with @task
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new(:due_at => Time.now)
    
    respond_with @task
  end

  # GET /tasks/1/edit
  def edit
    @task = current_user.tasks.find(params[:id])

    respond_with @task
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = Task.new(params[:task])
    @task.user = current_user
    
    respond_with @task do |format|
      if @task.save
        @contact = @task.contact
        @last_tasks = @contact.tasks.last_tasks if @contact.present?
        format.html { redirect_to(tasks_path, :notice => t('messages.created')) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = current_user.tasks.find(params[:id])

    respond_with @task do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(tasks_path, :notice => t('messages.updated')) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy
    @tasks = current_user.tasks.order("created_at DESC")
    
    respond_with @task do |format|
      format.html { redirect_to tasks_path }
    end
  end
  
  def get_tasks
    @start_at = Time.at(params['start'].to_i).to_formatted_s(:db)
    @end_at = Time.at(params['end'].to_i).to_formatted_s(:db)
    
    @tasks = Task.where(["due_at >= ? AND due_at <= ? AND completed = ?", @start_at, @end_at, false])
    tasks = []
    @tasks.each do |task|
      tasks << {:id => task.id, :title => task.name[0..13], :name => "", :start => "#{task.due_at.iso8601}", :end => "#{task.due_at.iso8601}", :allDay => (task.due_at.time == task.due_at.at_midnight.time), :recurring => false, :url => task_path(task)}
    end
    render :text => tasks.to_json
  end
  
  def complete
    @task = current_user.tasks.find(params[:id])
    respond_with @task do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(tasks_path, :notice => t('messages.task.completed')) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def postpone
    @task = current_user.tasks.find(params[:id])
    @days = params[:days]
    @due_at = @task.due_at + @days.to_i.day
    
    respond_with @task do |format|
      if @task.update_attribute(:due_at, @due_at)
        format.html { redirect_to(@task, :notice => t('messages.task.postponed')) }
      else
        format.html { render :action => "show" }
      end
    end
  end
  
  def comment
    @task = current_user.tasks.find(params[:id])
    @contact = @task.contact
    @comment = @task.comments.new(params[:comment])
    @comment.update_attribute(:user_id, current_user)
    
    respond_with @comment do |format|
      format.html { redirect_to([@task], :notice => t('messages.comment.created')) }
    end
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
  def sidebar_tasks()
    lista = ""
    links = {
      "1" => { :title => t("application.task.incomplete"), :path => tasks_path },
      "2" => { :title => t("application.task.this_week"), :path => week_tasks_path },
      "3" => { :title => t("application.task.next_week"), :path => next_week_tasks_path },
      "4" => { :title => t("application.task.completed"), :path => completed_tasks_path }
    }
    links.map do |key, value|
      classname = "selected" if value[:path] == request.fullpath
      last = "last" if key.to_i == links.size
      lista += "<li class=\"#{classname} #{last}\">#{link_to(value[:title], value[:path])}</li>"
    end
    lista.html_safe
  end
end

app/views/tasks/_form.html.erb
<% content_for :javascript do %>
	$(function(){
		$("textarea").elastic();
		
		$.datepicker.setDefaults( $.datepicker.regional[ "<%= I18n.locale %>" ] );
		$( "#datepicker" ).datepicker({
			altField: "#alternate",
			altFormat: "yy-mm-dd",
			showOtherMonths: true,
			selectOtherMonths: false,
			changeMonth: true,
			changeYear: true,
			dateFormat: "yy-mm-dd",
			defaultDate: "<%=l @task.due_at, :format => :datepicker %>"
		});
		
		$("#timepicker").mask("99:99");
	});
<% end %>

<% semantic_form_for @task do |form| %>

	<%= form.inputs :class => "column_left right_border", :style => "width: 270px; margin-right: 20px;" do %>
		<%= form.input :due_at_date, :as => :hidden, :input_html => { :id => "alternate" } %>
		<li>
			<%= form.label :due_at_date %>
			<div id="datepicker" style="width: 250px"></div>
		</li>
		<%= form.input :due_at_time, :as => :string, :input_html => { :style => "width: 240px", :id => "timepicker" } %>
	<% end %>
	
	<%= form.inputs :class => "column_left", :style => "" do %>
		<%= form.input :name, :input_html => { :rows => 4 } %>
		<% if !form.object.new_record? %>
		<%= form.input :completed %>
		<% end%>
		<div class="clear"></div>
	<% end %>
	
	<fieldset></fieldset>
	<hr />
	<div class="group navform wat-cf">
	  <%= submit_button %>
	</div>
<% end %>

app/views/tasks/_full_list.html.erb
<% if defined?(title) and tasks.size > 0 %>
<h3 class="general_border_radius task <%= "overdue" if defined?(overdue) %> <%= "today" if defined?(today) %>"><%= (defined?(overdue) and tasks.size > 1) ? title.pluralize : title %></h3>
<% end %>

<ul class="contact_show_list tasks full_list" style="width: 70%; margin: 0 auto;">
	<% tasks.each do |task| %>
		<li id="<%= dom_id task %>">
			<table>
			<tr>
			<% unless defined?(completed) %>
			<td class="complete_task ">
				<%= form_for task, :html => { :class => "edit_task" }, :url => complete_task_path(task), :remote => true do |form| %>
				<%= form.check_box :completed, :class => "complete", :title => t("application.to_complete_task") %>
				<% end %>
			</td>
			<% end %>
			<td class="task_content">
				<div class="list_options">
					<a href="<%= task_path(task) %>" class="list_option"><%=t "application.details" %></a>
				</div>
				<div class="text">
					<h4>
						<% if task.due_at.present? %>
							<% if task.due_at.year == Date.today.year %>
							<%= I18n.l task.due_at, :format => :long_no_time_no_year %>
							<% else %>
							<%= I18n.l task.due_at, :format => :long_no_time %>
							<% end %>
						<% end %>
						<% unless task.comments.empty? %>
							<%= inline_ui_icon("comment", :title => t("texts.task.has_comments")) %>
						<% end %>
					</h4>
				<p>
					<% if task.overdue? %>
					<img src="/images/icons/exclamation.png" title="<%= t "application.task.overdue" %>" class="tooltip"/>
					<% end %>
					<%= task.name %>
					<% if task.contact.present? %>
					<span class="gray_small"><%= link_to(task.contact.name, contact_path(task.contact)) %> <img src="/images/icons/user-card.png" style="vertical-align:text-bottom"/></span>
					<% end %>
				</p>
				</div>
			</td>
			</tr>
			</table>
		</li>
	<% end %>
</ul>

app/views/tasks/_inline_form.html.erb
<% content_for :javascript do %>
	$(function(){
		$.datepicker.setDefaults( $.datepicker.regional[ "<%= I18n.locale %>" ] );
		$( "#datepicker" ).datepicker({
			altField: "#alternate",
			altFormat: "yy-mm-dd",
			showOtherMonths: true,
			selectOtherMonths: false,
			changeMonth: true,
			changeYear: true
		});
		
		$("#timepicker").mask("99:99");
		
		$("#task_options a").live("click", function(e){
			e.preventDefault();
			$(this).parent().addClass("hidden");
			$("#task_date_select").removeClass("hidden");
		});
	});
<% end %>

<% semantic_form_for @task, :html => { :class => "inline" }, :remote => true do |form| %>

	<%= form.inputs :class => "column_left right_border", :style => "width: 270px; margin-right: 20px;" do %>
		<%= form.hidden_field :contact_id, :value => @contact.id %>
		<%= form.hidden_field :due_at_date, :id => "alternate" %>
		<%= form.input :due_at_date, :as => :hidden, :input_html => { :id => "alternate" } %>
		<li>
			<%= form.label :due_at_date %>
			<div id="datepicker" style="width: 250px"></div>
		</li>
		<span id="task_options" class="inline-options underline float_left"><a href="#"><%= t"application.set_time" %></a></span>
		<span id="task_date_select" class="hidden float_left">
		<label><%= t"application.at_time" %></label> <%= form.text_field :due_at_time, :id => "timepicker", :style => "width: 60px", :autocomplete => "off" %>
	<% end %>
	
	<%= form.inputs :class => "column_left", :style => "" do %>
		<%= form.input :name, :input_html => { :rows => 4 } %>
	<% end %>
	<hr class="clear" />
	<div class="group navform wat-cf right">
	  <%= submit_button :back => :none, :icon => "add", :label => t("application.add") %>
	</div>
<% end %>

app/views/tasks/_javascript.html.erb
$(function() {
	$(".contact_show_list li").live("mouseover mouseout", function(event){
		if (event.type == 'mouseover') {
			$(this).find(".list_options").show();
		} else {
			$(this).find(".list_options").hide();
		}
	});
	$("form input.complete").removeAttr("disabled");
	$("form input.complete").attr('checked', false);
	$("form input.complete").live("click", function(e){
		$(this).parents("form").filter(':first').submit();
		$(this).attr("disabled", true);
	});	
});

app/views/tasks/_list.html.erb
<%= content_for :javascript do %>
	$(function() {
		$(".tasks form input.complete").removeAttr("disabled");
		$(".tasks form input.complete").attr('checked', false);
		$(".tasks form input.complete").live("click", function(e){
			$(this).parents("form").filter(":first").submit();
			$(this).attr("disabled", true);
		});
	});
<% end %>

<div class="quick_links right">
	<ul>
		<li><a href="#" id="open_new_task_dialog"><%= t "texts.contact.new_task" %></a>
	</ul>
</div>
<h3><%= inline_ui_icon("color tasks") %> <%= t "application.tasks" %></h3>

<ul class="contact_show_list tasks">
	<% tasks.each do |task| %>
		<li id="<%= dom_id task %>">
			<table>
			<tr>
			<td class="complete_task">
				<%= form_for task, :html => { :class => "edit_task" }, :url => complete_task_path(task), :remote => true do |form| %>
				<%= form.check_box :completed, :class => "complete", :title => t("application.to_complete_task") %>
				<% end %>
			</td>
			<td class="task_content">
				<div class="list_options">
					<a href="<%= task_path(task) %>" class="list_option"><%=t "application.details" %></a>
				</div>
				<div class="text">
				<h4 class="<%= "overdue" if task.overdue? %>">
				<% if task.due_at.present? %>
					<% if task.due_at.year == Date.today.year %>
					<%= I18n.l task.due_at, :format => :short %>
					<% else %>
					<%= I18n.l task.due_at, :format => :short_with_year %>
					<% end %>
				<% end %>
				<% unless task.comments.empty? %>
					<%= inline_ui_icon("comment", :title => t("texts.task.has_comments")) %>
				<% end %>
				</h4>
				<p>
				<% if task.overdue? %>
				<img src="/images/icons/exclamation.png" title="<%= t "application.task.overdue" %>" class="tooltip"/>
				<% end %>
				<%= task.name %>
				</p>
				</div>
			</td>
			</tr>
			</table>
		</li>
	<% end %>
</ul>

app/views/tasks/_pagination.html.erb
<%= will_paginate tasks, :previous_label => t('pagination.previous'), :next_label => t('pagination.next') %>

app/views/tasks/_sidebar.html.erb
<% content_for :javascript do %>
	$(function() {
	});
<% end %>

<div class="block notice">
	<h3><%= t "application.show" %></h3>
	<ul class="navigation">
		<%= sidebar_tasks %>
	</ul>
</div>

app/views/tasks/comment.js.erb
<% @object_dom = dom_id(@comment) %>

$(".comment_form form")[0].reset();
$('.formtastic').valtastic();

$(".comments").html("<%= escape_javascript(render(:partial => "tasks/comments"))%>")
$("#<%= @object_dom %>").effect("highlight", {}, 1500);

app/views/tasks/completed.html.erb
<% content_for :javascript, render(:partial => "javascript") %>

<div class="block">
	<div class="content">
		<div class="content-header">
			<div class="control">
				<%= link_to_new(Task) %>
			</div>
			<h2 class="title">
				<%= t("application.tasks", :default => "Tasks")  %>
			</h2>
		</div>
		<div class="inner">
			<div id="data_view">
				<% if @completed.size > 0 %>
					<%= render :partial => "full_list", :locals => { :tasks => @completed, :title => t("application.task.completed"), :completed => true } %>
				<% end %>
			</div>
			<div id="data_pagination">
				<%= render :partial => "pagination", :locals => { :tasks => @completed } %>
			</div>
			<div class='wat-cf'></div>
		</div>
	</div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') %>

app/views/tasks/edit.html.erb
<div class="block">       
  <div class="content">
	<div class="content-header">
		<% if @task.contact.present? %>
    		<h2><%= t("application.edit", :default => "Edit") %> <%= t("activerecord.models.task", :default => "Task").downcase %> <%= t "application.about" %> <%= link_to @task.contact.name, @task.contact %></h2>
		<% else %>
			<h2><%= t("application.edit", :default => "Edit") %> <%= t("activerecord.models.task", :default => "Task").downcase %></h2>
		<% end %>
	</div>
    <div class="inner">
        <%= render :partial => "form" %>
    </div>
  </div>
</div>

<% content_for :sidebar do %>
	<div class="block notice">
		<ul class="navigation">
			<% if @task.contact.present? %>
			<li><%= link_to "#{t("application.see")} #{t("activerecord.models.contact").downcase}", @task.contact %></li>
			<% end %>
			<li class="last"><%= link_to t("application.task.see_all_tasks"), tasks_path %></li>
		</ul>
	</div>
<% end %>

app/views/tasks/index.html.erb
<% content_for :javascript, render(:partial => "javascript") %>

<div class="block">
	<div class="content">
		<div class="content-header">
			<div class="control">
				<%= link_to_new(Task) %>
			</div>
			<h2 class="title">
				<span class="header_icon tasks"></span>
				<%= t("application.tasks", :default => "Tasks")  %>
			</h2>
		</div>
		<div class="inner">
			<% if @empty %>
			<div id="empty_data" class="tasks">

				<div class="icon"><%= image_tag "empty_tasks.jpg" %></div>
				<div class="arrow"></div>
				<div class="text">
					<h1>Nenhuma tarefa em aberto</h1>
					<p>Store every conversation, email, call, meeting, document, and deal you’ve ever had with a contact. With Highrise you’ll always know who you talked to, what was said, and when to follow-up next.</p>
				</div>
			</div>
			<div class="clear"></div>
			<% end %>
			
			<div id="data_view">
				<div id="overdue_frame">
				<%= render :partial => "full_list", :locals => { :title => t("application.task.show_overdue"), :tasks => @overdue, :overdue => true } %>
				</div>
				<div id="today_frame">
				<%= render :partial => "full_list", :locals => { :title => t("application.task.today"), :tasks => @today, :today => true } %>
				</div>
				<div id="this_week_frame">
				<%= render :partial => "full_list", :locals => { :title => t("application.task.this_week"), :tasks => @week } %>
				</div>
				<div id="next_week_frame">
				<%= render :partial => "full_list", :locals => { :title => t("application.task.next_week"), :tasks => @next_week } %>
				</div>
				<div id="later_frame">
				<%= render :partial => "full_list", :locals => { :title => t("application.task.later"), :tasks => @later } %>
				</div>
			</div>
		</div>
	</div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') %>

app/views/tasks/next_week.html.erb
<% content_for :javascript, render(:partial => "javascript") %>

<div class="block">
	<div class="content">
		<div class="content-header">
			<div class="control">
				<%= link_to_new(Task) %>
			</div>
			<h2 class="title">
				<%= t("application.tasks", :default => "Tasks")  %>
			</h2>
		</div>
		<div class="inner">
			<div id="data_view">
				<% if @next_week.size > 0 %>
					<%= render :partial => "full_list", :locals => { :title => t("application.task.next_week"), :tasks => @next_week } %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') %>

app/views/tasks/show.html.erb
<%= content_for :javascript do %>
	$(function() {
		$("#dialog-postpone").dialog({
			autoOpen: false,
			draggable: false,
			width: 500,
			height: 160,
			modal: true
		});
		
		$("#postpone_link").click(function(e){
			e.preventDefault();
			$("#dialog-postpone").dialog("open");
		});
	});
<% end %>
<div class="block">       
  <div class="content">
	<div class="content-header">
		<% if @task.contact.present? %>
    		<h2><%= t("activerecord.models.task", :default => "Task") %> <%= t "application.about" %> <%= link_to @task.contact.name, contact_path(@contact) %></h2>
		<% else %>
			<h2><%= t("activerecord.models.task", :default => "Task") %></h2>
		<% end %>
	</div>
    <div class="inner">
        <h4 class="nice_blue">
			<strong><%=t "activerecord.attributes.task.due_at" %>:</strong>
			<% if @task.due_at.time == @task.due_at.at_midnight.time %>
			<%=l @task.due_at, :format => :short_with_year %>
			<% else %>
			<%=l @task.due_at %>
			<% end %>
		</h4>
		
		<%= simple_format @task.name %>
		
		<%= form_for @task, :html => { :class => "inline" } do |form| %>
		<% if @task.completed %>
			<%= form.hidden_field :completed, :value => false %>
			<%= submit_button :label => t("application.task.reopen"), :back => :none, :icon => "back", :onclick => "return confirm('#{t("application.task.confirm_reopen")}')" %>
		<% else %>
			<%= form.hidden_field :completed, :value => true %>
			<%= submit_button :label => t("application.task.complete"), :back => :none %>
		<% end %>
		<% end %>
		
		<div class="clear space"></div>

		<a href="#" id="postpone_link" class="button inline"><%= inline_ui_icon("forward") %> <%= t("application.task.postpone") %></a>
		
		<hr class="clear" style="padding-top: 15px" />
		
		<div class="data_details gray_small">
			<p><strong><%=t "activerecord.attributes.note.created_at" %>:</strong> <%=l @task.created_at %></p>
			<% if @task.created_at != @task.updated_at %>
			<p><strong><%=t "activerecord.attributes.note.updated_at" %>:</strong> <%=l @task.updated_at %></p>
			<% end %>
		</div>
		<hr />
		
		<div class="comment_form">
			<h3><%= t "texts.comment.new" %> <%= t "texts.task.about_this" %></h3>

			<% semantic_form_for @comment, :html => {:id => "add_new_comment", :class => "inline"}, :url => comment_task_path(@task), :remote => true do |form| %>
				<%= form.inputs do %>
				<%= form.input :comment, :label => false, :input_html => { :rows => 2 } %>
				<div class="right"><%= submit_button :back => :none, :icon => "add", :label => "Adicionar" %></div>
				<% end %>
			<% end %>
		</div>
		<div class="clear"></div>
		<hr />
		<div class="comments">
			<%= render :partial => "comments" %>
		</div>
		
		
    </div>
  </div>
</div>

<div id="dialog-postpone" title="<%=t "application.task.postpone_title" %>">
	<%= form_tag postpone_task_path(@task), :class => "popup inline" do |form| %>
		<p>
			Adiar esta tarefa, com prazo para <strong><%=l @task.due_at, :format => :short_with_year %></strong>, em: 
			<%= text_field_tag :days, '', :style => "margin: 0 10px; width: 20px;" %> dias
		</p>
		
		<div class="group navform wat-cf">
		  <%= submit_button :label => t("application.postpone"), :back => :none, :icon => :forward %>
		</div>
	<% end %>
</div>

<% content_for :sidebar do %>
	<div class="block notice">
		<ul class="navigation">
			<% if @task.contact.present? %>
			<li><%= link_to "#{t("application.see")} #{t("activerecord.models.contact").downcase}", @task.contact %></li>
			<% end %>
			<li><%= link_to t("application.task.see_all_tasks"), tasks_path %></li>
			<li><%= link_to "Alterar tarefa", edit_task_path(@task) %></li>
			<li class="last"><%= link_to "Remover tarefa", task_path(@task), :method => :delete, :confirm => "#{t("application.confirm", :default => "Are you sure?")}" %></li>
		</ul>
	</div>
<% end %>

app/views/tasks/week.html.erb
<% content_for :javascript, render(:partial => "javascript") %>

<div class="block">
	<div class="content">
		<div class="content-header">
			<div class="control">
				<%= link_to_new(Task) %>
			</div>
			<h2 class="title">
				<%= t("application.tasks", :default => "Tasks")  %>
			</h2>
		</div>
		<div class="inner">
			<div id="data_view">
				<% if @week.size > 0 %>
					<%= render :partial => "full_list", :locals => { :title => t("application.task.this_week"), :tasks => @week } %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') %>