config/routes.rb
Organizer::Application.routes.draw do

  resources :suit_status_changes

  resources :protocols

  resources :suits

  resources :events

  resources :categories
  
  resources :comments, :only => [:destroy]

  resources :users do
    collection do
      put :update_profile
    end
  end

  resources :contacts do
    resources :notes do
      member do
        post :comment
      end
    end
    member do
      get :confirm_destroy
      get :avatar
      put :favorite
    end
    collection do
      post :print
    end
  end

  resources :preferences do
    collection do
      get :profile
      get :dashboard
      put :update_dashboard
    end
  end

  resources :tasks do
    member do
      put :complete
      post :comment
      post :postpone
    end
    collection do
      get :get_tasks
      get :week
      get :next_week
      get :completed
    end
  end
  
  
  match '/calendar' => 'calendar#index', :as => :calendar
  match '/summary' => 'home#summary', :as => :summary
  match '/profile' => 'users#profile', :as => :profile
  
  match '/search' => 'home#search', :as => :search
  match '/search/city' => 'home#search_city', :as => :search_city
  match '/search/occupation' => 'home#search_occupation', :as => :search_occupation
  match '/search/weather' => 'home#search_weather', :as => :search_weather

  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :home, :only => [:index]

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :require_user
  respond_to :html, :js
  
  def index
    @overdue_tasks = current_user.tasks.overdue
    @today_tasks = current_user.tasks.incomplete.due_to_today.limit(5)
    @this_week_tasks = current_user.tasks.incomplete.due_to_this_week.limit(5)
    @next_week_tasks = current_user.tasks.incomplete.due_to_next_week.limit(5)
    
    @today_birthdays = current_user.contacts.select{ |c| c.has_birthday_today? }
    @tomorrow_birthdays = current_user.contacts.select{ |c| c.has_birthday_tomorrow? }
    @next_birthdays = current_user.contacts.select{ |c| c.birthday.present? and !c.has_birthday_today? and !c.has_birthday_tomorrow? }.sort_by(&:next_birthday)[0..5]
        
    @last_contacts = current_user.contacts.favorites.main
    # ptbr_client = Weatherman::Client.new :lang => 'pt-br'
    # res = ptbr_client.lookup_by_woeid 455827
    # @location = res.location['city'] + ', ' + res.location['region']
    # @condition = res.condition
    # @d_or_n = Time.zone.now.hour >= 18 ? "n" : "d"
    # @weather_icon = "http://l.yimg.com/a/i/us/nws/weather/gr/#{ @condition['code'] }#{ @d_or_n }.png"
  end
  
  def summary
    @when = params[:when] || 1
    
    @start = Time.zone.today.beginning_of_month
    @end = Time.zone.today.end_of_month+1.day
    
    case @when
      when "2" then # last month
        @start = (Time.zone.today.beginning_of_month-1.day).beginning_of_month
        @end = (Time.zone.today.beginning_of_month-1.day).end_of_month+1.day
      when "3" then # 2 months ago
        @start = ((Time.zone.today.beginning_of_month-1.day).beginning_of_month-1.day).beginning_of_month
        @end = ((Time.zone.today.beginning_of_month-1.day).beginning_of_month-1.day).end_of_month+1.day
    end
    
    @contacts = current_user.contacts.where( :created_at => (@start)..(@end) ).order("created_at DESC")
    @notes = current_user.notes.where( :date => (@start)..(@end) ).order("date DESC")
    @tasks = current_user.tasks.where( :due_at => (@start)..(@end) ).order("due_at DESC")
  end
  
  def search
    @search_contacts = current_user.contacts.search_everything(params[:content])
    @search_notes = current_user.notes.search_everything(params[:content])
    @search_tasks = current_user.tasks.search_everything(params[:content])
  end
  
  def search_city
    @data = Contact.search_by(:city, params[:term]).select{ |c| c.city.present? }.collect{ |c| c.city }.uniq
    render :json => @data.collect{ |c| {:value => "#{c}", :label => "#{c}"} }
  end
  
  def search_occupation
    @data = Contact.search_by(:occupation, params[:term]).select{ |c| c.occupation.present? }.collect{ |c| c.occupation }.uniq
    render :json => @data.collect{ |c| {:value => "#{c}", :label => "#{c}"} }
  end
  
  def search_weather
    if !params[:term].empty?
      require 'net/http'
      require 'rexml/document'
    
      @url = "http://xoap.weather.com/search/search?where=#{params[:term]}"
      response = Net::HTTP.get_response(URI.parse(URI.encode(@url))).body
      xml = REXML::Document.new response
      @locations = []
      xml.elements['search'].elements.each('loc') do |e|
        @locations << { :id => e.attributes['id'], :value => e.text, :label => e.text }
      end
      render :json => @locations
    else
      render :nothing => true
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def sidebar_home()
	lista = ""
    links = {
      "1" => { :title => t("application.general"), :path => root_path },
      "2" => { :title => t("application.home.summary"), :path => summary_path }
    }
    links.map do |key, value|
      classname = "selected" if value[:path] == request.fullpath
      last = "last" if key.to_i == links.size
      lista += "<li class=\"#{classname} #{last}\">#{link_to(value[:title], value[:path])}</li>"
    end
    lista.html_safe
  end
end

app/views/home/_search.html.erb
<div class="search_results">

	<div class="home_column border">
	<% if @search_contacts %>
		<h3><%= t"application.contacts" %></h3>
		<ul class="home_list">
			<% @search_contacts.each do |contact| %>
			<li><%= link_to contact.name, contact_path(contact) %></li>
			<% end %>
		</ul>
		<% if @search_contacts.size == 0 %>
		<p class="italic"><%= t"application.no_results" %></p>
		<% end %>
	<% end %>
	</div>

	<div class="home_column border">
	<% if @search_tasks %>
		<h3><%= t"application.tasks" %></h3>
		<ul class="home_list">
			<% @search_tasks.each do |task| %>
			<li>
				<% if task.contact.present? %>
				<%= link_to truncate(task.name, :length => 60), contact_path(task.contact) %>
				<span class="gray_small">(<%= task.contact.name %>)</span>
				<% else %>
				<%= link_to truncate(task.name, :length => 60), tasks_path %>
				<% end %>
			</li>
			<% end %>
		</ul>
		<% if @search_tasks.size == 0 %>
		<p class="italic"><%= t"application.no_results" %></p>
		<% end %>
	<% end %>
	</div>

	<div class="home_column">
	<% if @search_notes %>
		<h3><%= t"application.notes" %></h3>
		<ul class="home_list">
			<% @search_notes.each do |note| %>
			<li><%= link_to truncate(note.name, :length => 50), contact_path(note.contact) %> <span class="gray_small">(<%= note.contact.name %>)</span></li>
			<% end %>
		</ul>
		<% if @search_notes.size == 0 %>
		<p class="italic"><%= t"application.no_results" %></p>
		<% end %>
	<% end %>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>

app/views/home/_sidebar.html.erb
<% content_for :javascript do %>
	$(function(){
		<% if current_user.preference.present? and current_user.preference.weather_location.present? %>
			$(".weather").weatherfeed(['<%= current_user.preference.weather_location %>']);
		<% end %>
		
		$(".search_results_wrapper").dialog({
			autoOpen: false,
			draggable: false,
			width: "60%",
			minWidth: 300,
			height: 360,
			minHeight: 360,
			modal: true
		});
	});
<% end %>

<div class="notice block">
  <h3><%= t"application.dashboard" %></h3>
  <ul class="navigation">
    <%= sidebar_home %>
  </ul>
</div>

<div class="today">
	<div class="day">
		<%= "%02d" % Date.today.day.to_i %>
	</div>
	<div class="caption">
		<%= l(Date.today, :format => :weekday) %>
	</div>
	<div class="caption2">
		<%= l(Date.today, :format => :month_year) %>
	</div>
	<div class="clear"></div>
</div>

<% if current_user.preference.present? and current_user.preference.weather_location.present? %>
	<div class="weather"></div>
<% end %>

app/views/home/index.html.erb
<% content_for :javascript do %>
	$(function(){
		$(".search_everything").defaultValue({'value' : '<%= t"application.search_everything" %>'});
		
		$(".search_results_wrapper").dialog({
			autoOpen: false,
			draggable: false,
			width: "60%",
			minWidth: 300,
			height: 360,
			minHeight: 360,
			modal: true
		});
	});
<% end %>

<div class="block">
	<div class="content"> 
		<div class="content-header">
			     
			<div class="home_search">
				<%= form_tag search_path, :remote => true do |form| %>
				<div class="fake_search">
					<div class="column_left" style="width: 95%;">
					<%= text_field_tag "content", "", { :class => "search_everything", :autocomplete => "off" } %>
					</div>
					<div class="column_right" style="width: 25px;">
					<%= image_submit_tag("/images/icons/search.png", :style => "width:16px;height:16px;margin-top:3px;") %>
					</div>
					<div class="clear"></div>
				</div>
				<% end %>
				<div class="search_results_wrapper" title="<%= t"application.search_title" %>"></div>
			</div>
			
		</div>
		<div class="inner">
			
			<div class="home_column block">
				<div class="content-header">
					<h3><%= inline_ui_icon("color tasks") %> Tarefas</h3>
				</div>
				<div class="inner">
					<ul class="home_list">
						<% if @overdue_tasks.size == 0 and @today_tasks.size == 0 && @this_week_tasks.size == 0 %>
							<p class="gray_small"><%= t("application.home.no_task")%></p>
						<% end %>
						
						<% if @overdue_tasks.size > 0 %>
						<h3 class="red"><%= t"application.task.overdue_plural" %></h3>
						<% @overdue_tasks.each do |task| %>
						<li>
							<%= link_to truncate(task.name, :length => 50), tasks_path %>
							<%= " - #{task.contact.first_name}" if task.contact.present? %>
							<span class="gray_small">(<%=l task.due_at, :format => :short %>)</span>
						</li>
						<% end %>
					<% end %>
					</ul>
					
					<ul class="home_list">
						<% if @today_tasks.size > 0 %>
						<h3><%= t"application.today" %><span class="gray_small">, <%=l Date.today, :format => :short_desc %></span></h3>
						<% @today_tasks.each do |task| %>
						<li>
							<%= link_to truncate(task.name, :length => 50), tasks_path %>
							<%= " - #{task.contact.first_name}" if task.contact.present? %>
						</li>
						<% end %>
						<% end %>
					</ul>
					
					<ul class="home_list">
						<% if @this_week_tasks.size > 0 %>
						<h3><%= t"application.this_week" %></h3>
						<% @this_week_tasks.each do |task| %>
						<li><%= link_to truncate(task.name, :length => 50), tasks_path %>
							<%= " - #{task.contact.first_name}" if task.contact.present? %>
							<span class="gray_small">(<%=l task.due_at, :format => :short %>)</span></li>
						<% end %>
						<% end %>
					</ul>
					
					<ul class="home_list">
						<% if @next_week_tasks.size > 0 %>
						<h3><%= t"application.next_week" %></h3>
						<% @next_week_tasks.each do |task| %>
						<li><%= link_to truncate(task.name, :length => 50), tasks_path %>
							<%= " - #{task.contact.first_name}" if task.contact.present? %>
							<span class="gray_small">(<%=l task.due_at, :format => :short %>)</span></li>
						<% end %>
						<% end %>
					</ul>
				</div>
			</div>
			
			<div class="home_column block">
				<div class="content-header"><h3><img src="/images/icons/calendar.png" /> Aniversários</h3></div>
				<div class="inner">
					<% if @today_birthdays.size == 0 and @next_birthdays.size == 0 %>
						<p class="gray_small"><%= t("application.home.no_birthday")%></p>
					<% end %>
					
					<% if @today_birthdays.size > 0 %>
					<h3>Hoje<span class="gray_small">, <%=l Date.today, :format => :short_desc %></span></h3>
					<ul class="home_list">
					<% @today_birthdays.each do |contact| %>
						<li><%= link_to contact.name, contact_path(contact) %><span class="gray_small">, <%= contact.age %> anos</li>
					<% end %>
					</ul>
					<% end %>
					
					<% if @tomorrow_birthdays.size > 0 %>
					<h3>Amanhã<span class="gray_small">, <%=l Date.tomorrow, :format => :short_desc %></span></h3>
					<ul class="home_list">
					<% @tomorrow_birthdays.each do |contact| %>
						<li><%= link_to contact.name, contact_path(contact) %><span class="gray_small">, <%= contact.age+1 %> anos</li>
					<% end %>
					</ul>
					<% end %>
					
					<% if @next_birthdays.size > 0 %>
					<% if @today_birthdays.size > 0 or @tomorrow_birthdays.size > 0 %>
					<hr class="space" />
					<% end %>
					<ul class="home_list">
					<% @next_birthdays.each do |contact| %>
						<li><%= link_to contact.name, contact_path(contact) %> <span class="gray_small">(<%=l contact.birthday, :format => :short %>)</span></li>
					<% end %>
					</ul>
					<% end %>
				</div>
			</div>
			
			<div class="home_column block">
				<div class="content-header">
					<h3><%= inline_ui_icon("color favorite_on") %> Contatos favoritos</h3>
				</div>
				<div class="inner">
					<% if @last_contacts.size == 0 %>
						<p class="gray_small"><%= t("application.home.no_favorite_contact")%></p>
					<% end %>
					
					<ul class="home_list">
						<% @last_contacts.each do |contact| %>
						<li><%= link_to contact.name, contact_path(contact) %></li>
						<% end %>
					</ul>
				</div>
			</div>

			<div class="clear"></div>
		</div>
	</div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/home/search.js.erb
$(".search_results_wrapper").html("<%= escape_javascript(render(:partial => "search"))%>");

$(".search_results_wrapper").dialog("open");

app/views/home/summary.html.erb
<% content_for :javascript do %>
	$(function(){
		$("form select").change(function(){
			$(this).parents("form").filter(":first").submit();
		});
	});
<% end %>

<div class="block">
	<div class="content"> 
		<div class="content-header">
			<div class="control">
				<% form_tag do %>
					<%= select_tag "when", options_for_select([["Este mês", "1"], ["Mês passado", "2"], ["Dois meses atrás", "3"]], @when) %>
				<% end %>
			</div>
			<h2>
				<span class="header_icon clock"></span>
				<%= t("application.home.time_summary") %>
			</h2>
		</div>
		<div class="inner summary">
			<h2 class="nice_blue">
				<%=l @start %> - <%=l @end %>
			</h2>

			<h3 class="space_t">Contatos cadastrados</h3>
			<hr class="space" />
			
			<ul class="home_list">
			<% @contacts.each do |c| %>
				<li><%= link_to c.name, contact_path(c) %></li>
			<% end %>
			</ul>
			
			<h3 class="space_t">Notas cadastradas</h3>
			<hr class="space" />
			
			<table class="home_list">
				<% @notes.each do |n| %>
				<tr>
					<td class="arrow"></td>
					<td style="width: 50px">
						<strong><%= l(n.date, :format => :short) %></strong>
					</td>
					<td>
						<%= link_to truncate(n.name, :length => 80), contact_note_path(n.contact, n) %>
					</td>
					<td>
						<span class="gray_small"><%= link_to(n.contact.name, contact_path(n.contact)) %> <img src="/images/icons/user-card.png" style="vertical-align:text-bottom"/></span>
					</td>
				</tr>
				<% end %>
			</table>
			
			<h3 class="space_t">Tarefas</h3>
			<hr class="space" />
			
			<ul class="home_list">
			<% @tasks.each do |t| %>
				<li><a href="<%= task_path(t) %>" class="<%= t.completed ? "strike" : "" %>"><strong><%= l(t.due_at, :format => :short) %></strong> <%= truncate(t.name, :length => 80) %></a></li>
			<% end %>
			</ul>
			
		</div>
	</div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>