config/routes.rb
Organizer::Application.routes.draw do

  resources :suit_status_changes

  resources :protocols

  resources :suits

  resources :events

  resources :categories
  
  resources :comments, :only => [:destroy]

  resources :users do
    collection do
      put :update_profile
    end
  end

  resources :contacts do
    resources :notes do
      member do
        post :comment
      end
    end
    member do
      get :confirm_destroy
      get :avatar
      put :favorite
    end
    collection do
      post :print
    end
  end

  resources :preferences do
    collection do
      get :profile
      get :dashboard
      put :update_dashboard
    end
  end

  resources :tasks do
    member do
      put :complete
      post :comment
      post :postpone
    end
    collection do
      get :get_tasks
      get :week
      get :next_week
      get :completed
    end
  end
  
  
  match '/calendar' => 'calendar#index', :as => :calendar
  match '/summary' => 'home#summary', :as => :summary
  match '/profile' => 'users#profile', :as => :profile
  
  match '/search' => 'home#search', :as => :search
  match '/search/city' => 'home#search_city', :as => :search_city
  match '/search/occupation' => 'home#search_occupation', :as => :search_occupation
  match '/search/weather' => 'home#search_weather', :as => :search_weather

  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :home, :only => [:index]

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

  root :to => "home#index"

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.datetime_select :end_at %>
  </div>
  <div class="field">
    <%= f.label :all_day %><br />
    <%= f.check_box :all_day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_pagination.html.erb
<%= will_paginate @events, :params => { :controller => "events" }, :previous_label => t('pagination.previous'), :next_label => t('pagination.next') %>

app/views/events/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/events/_table.html.erb
<table class = "table">
	<tr>
		<th>
			<%= t("activerecord.attributes.event.name", :default => t("activerecord.labels.name", :default => "Name")) %>
		</th>
		<th><%= t("activerecord.attributes.event.description", :default => "Descrição")  %></th>
		<th class  = "last">&nbsp;</th>
	</tr>
	<% @events.each do |event| %>
	<tr class   = "<%= cycle("odd", "even") %>">
		<td>
			<%= link_to event.name, edit_event_path(event) %>
		</td>
		<td>
			<%= truncate(event.description.gsub(/<\/?[^>]*>/, ""), :length => 70, :omission => "...").html_safe if event.description.present? %>
		</td>
		<td class  = "last">
			<%= link_to "#{t("application..show", :default => "Show")}", event_path(event) %> |
			<%= link_to "#{t("application..edit", :default => "Edit")}", edit_event_path(event) %> |
			<%= link_to "#{t("application..delete", :default => "Delete")}", event_path(event), :remote => true, :method => :delete, :confirm => "#{t("application..confirm", :default => "Are you sure?")}" %>
		</td>
	</tr>          
	<% end -%>
</table>

app/views/events/destroy.js.erb
$("#data_view").html("<%= escape_javascript( render(:partial => "table") ) %>");
$("#data_pagination").html("<%= escape_javascript( render(:partial => "pagination") ) %>");
$(".pagination a").attr('data-remote', 'true');

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Start at</th>
    <th>End at</th>
    <th>All day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= event.title %></td>
    <td><%= event.description %></td>
    <td><%= event.start_at %></td>
    <td><%= event.end_at %></td>
    <td><%= event.all_day %></td>
    <td><%= link_to 'Show', event %></td>
    <td><%= link_to 'Edit', edit_event_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/index.js.erb
$("#data_view").html("<%= escape_javascript( render(:partial => "table") ) %>");
$("#data_pagination").html("<%= escape_javascript( render(:partial => "pagination") ) %>");
$(".pagination a").attr('data-remote', 'true');

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Start at:</b>
  <%= @event.start_at %>
</p>

<p>
  <b>End at:</b>
  <%= @event.end_at %>
</p>

<p>
  <b>All day:</b>
  <%= @event.all_day %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>